### ISSUE TITLE
[Ags] Roadmap

### ISSUE THREAD

**Issue by jilv220** [jilv220/dotfiles#2]
## Essential
- [x] Workspace
- [x] Systray
- [x] Power
  - [x] Lock/logout/suspend 
  - [x] Finish keyboard shortcuts
- [ ] Panel
  - [ ] Context menu
  - [ ] Middle click launch new instance
  - [ ] Limit max indicator
- [ ] Media
  - [x] Player title length not fixed
  - [x] Per Application Audio Mixer
  - [ ] Match button style
  - [ ] Click to mute / unmute audio/stream
- [ ] Battery
  - [ ] UI
  - [ ] Power Profile

## Low priority
- [ ] Calendar
  - [ ] Match the UI with cosmic
- [ ] Wi-Fi (nm-applet is good enough)
